namespace SpriteKind {
    export const tree = SpriteKind.create()
    export const FallenTree = SpriteKind.create()
    export const BronzeAxe = SpriteKind.create()
    export const Home = SpriteKind.create()
    export const 钓鱼竿类型 = SpriteKind.create()
    export const 挖矿镐类型 = SpriteKind.create()
    export const 矿脉类型 = SpriteKind.create()
    export const 钓鱼台类型 = SpriteKind.create()
    export const 鱼类型 = SpriteKind.create()
    export const 煤碳类型 = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.tree, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        sprite.sayText("砍倒啦", 1000, false)
        otherSprite.setImage(img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            .......ee.......
            ......eeee......
            .....eeeeee.....
            .......ee.......
            `)
        otherSprite.setKind(SpriteKind.FallenTree)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.钓鱼台类型, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        sprite.sayText("钓鱼啦", 1000, false)
        pause(1000)
        fishSprite = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . c c c c . . . . . . . . 
            . . . c d d d d c c . . . . . . 
            . . . c d c c c c c c . . . . . 
            . . . c c d 4 4 4 4 c c . . . . 
            c c . c 1 4 4 4 4 4 d 4 c . . . 
            c 4 c 1 d 4 4 4 4 1 4 4 4 c . . 
            c 4 c 1 4 4 4 4 4 1 4 4 4 4 c . 
            f 4 4 1 4 4 4 4 4 1 4 4 4 4 4 f 
            f 4 f 1 4 4 4 c c 1 4 f 4 4 4 f 
            f 4 f d 4 4 f 4 4 1 4 4 4 4 4 f 
            f f f f d 4 f 4 c 1 4 4 4 4 f . 
            . . c f c 4 f f 4 4 d 4 f f . . 
            . . c b d c 4 4 4 4 f f . . . . 
            . . c d d d f f f f . . . . . . 
            . . . c c c . . . . . . . . . . 
            `, SpriteKind.鱼类型)
        tiles.placeOnTile(fishSprite, tiles.getTileLocation(5, 3))
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.挖矿镐类型, function (sprite, otherSprite) {
    otherSprite.destroy()
    sprite.setImage(img`
        ....................................
        .......fff..........................
        ....fffff2f.........................
        ..ffeeeee22ff.......................
        .ffeeeeee222ff....f.e...............
        .feeeefffeeeef...fff1...............
        .fffffeee2222ef.f.1ff1..............
        fffe222fffffe2f..1e.ff1.............
        fffffffffeeefff..ee.fff.............
        fefe44ebbf44eef.1e...ff.............
        .fee4d4bbfddef..ee...f..............
        ..feee4dddddfee.e...................
        ...f2222222eedd1e...................
        ...f444445e44ddee...................
        ...ffffffffeeeee....................
        ...fff...ff.........................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.钓鱼竿类型, function (sprite, otherSprite) {
    otherSprite.destroy()
    sprite.setImage(img`
        ....................................
        .......fff..........................
        ....fffff2f.........................
        ..ffeeeee22ff.....1f................
        .ffeeeeee222ff....e.f...............
        .feeeefffeeeef....e.f...............
        .fffffeee2222ef...e.f...............
        fffe222fffffe2f..1e.f...............
        fffffffffeeefff..e..f...............
        fefe44ebbf44eef..e..f...............
        .fee4d4bbfddef...e..f...............
        ..feee4dddddfee.1e..f...............
        ...f2222222eedd1e...22..............
        ...f444445e44ddee...221.............
        ...ffffffffeeeee.....11.............
        ...fff...ff.........................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.BronzeAxe, function (sprite, otherSprite) {
    otherSprite.destroy()
    sprite.setImage(img`
        ....................................
        .......fff..........................
        ....fffff2f.........................
        ..ffeeeee22ff........e..............
        .ffeeeeee222ff...b..ee..............
        .feeeefffeeeef..bfbeee..............
        .fffffeee2222ef.bffebbbbb...........
        fffe222fffffe2f.bfeffffffb..........
        fffffffffeeefff.befffffffb..........
        fefe44ebbf44eef..fbffffffb..........
        .fee4d4bbfddef...e.bffffb...........
        ..feee4dddddfee.fe..bbfb............
        ...f2222222eeddef.....b.............
        ...f444445e44ddef...................
        ...ffffffffeeeee....................
        ...fff...ff.........................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        ....................................
        `)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.矿脉类型, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        sprite.sayText("挖矿啦", 1000, false)
        pause(1000)
        coalSprite = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . c c c . . . . . . 
            . . . . . . a b a a . . . . . . 
            . . . . . c b a f c a c . . . . 
            . . . . c b b b f f a c c . . . 
            . . . . b b f a b b a a c . . . 
            . . . . c b f f b a f c a . . . 
            . . . . . c a a c b b a . . . . 
            . . . . . . c c c c . . . . . . 
            . . . . . . . c . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.煤碳类型)
        coalSprite.setPosition(otherSprite.x, otherSprite.y)
        otherSprite.destroy()
    }
})
let coalSprite: Sprite = null
let fishSprite: Sprite = null
custom.prepareScene()
custom.plantTrees()
custom.returnAxe()
let heroSprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
heroSprite.z = 100
tiles.placeOnTile(heroSprite, tiles.getTileLocation(1, 3))
scene.cameraFollowSprite(heroSprite)
controller.moveSprite(heroSprite)
